### ISSUE TITLE
Messages over 40 characters (including padding) overflow to a new line

### ISSUE THREAD

**Issue by ziyadedher** [ziyadedher/rpi-display-projects#1]
Trying to display a message that is greater than 38 characters (subtract two for padding) will loop to the next line.

Need to fix it in `controller.py`.

**Comment by K-log** [comment]
I have a quick question about the issue. Is the bug that the message wraps to the next line because it is too long or is it that the message gets cut off and you need it to wrap to the next line?

**Comment by ziyadedher** [comment]
It wraps automatically on the Raspberry Pi once a line exceeds 40 chars, so it messes up with the `log` system.
